services:
  db:
    image: postgres:15
    container_name: shain-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shain_db
    volumes:
      # Mac側の ./docker/db/data フォルダにデータを保存
      - ./docker/db/data:/var/lib/postgresql/data
      # Mac側の ./docker/db/init フォルダにあるSQLを起動時に実行
      - ./docker/db/init:/docker-entrypoint-initdb.d